// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa7rzw3oC2OoHCMORqRRlVpT_RbuI_6H4',
    appId: '1:926234704646:web:9490a911c859bd6917bc87',
    messagingSenderId: '926234704646',
    projectId: 'resconnect-d0bd8',
    authDomain: 'resconnect-d0bd8.firebaseapp.com',
    storageBucket: 'resconnect-d0bd8.appspot.com',
    measurementId: 'G-PY0L7M573T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8MOtvDHV3xXWP9rHRXPt-5aAs5v1eTfg',
    appId: '1:926234704646:android:d56a92b64bc21f3f17bc87',
    messagingSenderId: '926234704646',
    projectId: 'resconnect-d0bd8',
    storageBucket: 'resconnect-d0bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRFfOtH6Q-PWH9f6hf4UCJ2w530txzOw',
    appId: '1:926234704646:ios:15507f91086344e517bc87',
    messagingSenderId: '926234704646',
    projectId: 'resconnect-d0bd8',
    storageBucket: 'resconnect-d0bd8.appspot.com',
    iosBundleId: 'com.example.resconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRFfOtH6Q-PWH9f6hf4UCJ2w530txzOw',
    appId: '1:926234704646:ios:15507f91086344e517bc87',
    messagingSenderId: '926234704646',
    projectId: 'resconnect-d0bd8',
    storageBucket: 'resconnect-d0bd8.appspot.com',
    iosBundleId: 'com.example.resconnect',
  );
}
